title: ePCR 2.0
#logo
description: UX Project to Redefine the ePCCR Data Capture System for Patient Care Reports Used by Emergency Responders
#show_downloads: true
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
